In [1]:
pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
Requirement already satisfied: requests in c:\anaconda\lib\site-packages (from vaderSentiment) (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\anaconda\lib\site-packages (from requests->vaderSentiment) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda\lib\site-packages (from requests->vaderSentiment) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda\lib\site-packages (from requests->vaderSentiment) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\anaconda\lib\site-packages (from requests->vaderSentiment) (1.26.7)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install textblob

Collecting textblob
  Downloading textblob-0.17.1-py2.py3-none-any.whl (636 kB)
Requirement already satisfied: nltk>=3.1 in c:\anaconda\lib\site-packages (from textblob) (3.6.5)
Requirement already satisfied: click in c:\anaconda\lib\site-packages (from nltk>=3.1->textblob) (8.0.3)
Requirement already satisfied: joblib in c:\anaconda\lib\site-packages (from nltk>=3.1->textblob) (1.1.0)
Requirement already satisfied: regex>=2021.8.3 in c:\anaconda\lib\site-packages (from nltk>=3.1->textblob) (2021.8.3)
Requirement already satisfied: tqdm in c:\anaconda\lib\site-packages (from nltk>=3.1->textblob) (4.62.3)
Requirement already satisfied: colorama in c:\anaconda\lib\site-packages (from click->nltk>=3.1->textblob) (0.4.4)
Installing collected packages: textblob
Successfully installed textblob-0.17.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
import numpy as np
import re
import pandas as pd
from textblob import TextBlob
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.metrics import accuracy_score

In [ ]:
from google.colab import files
files = files.upload()

In [ ]:
from google.colab import files 
files=files.upload()

In [11]:
stock = pd.read_csv('Dow Jones Industrial Average Historical Data.csv')
news=pd.read_csv('DJIA_table.csv', encoding = 'unicode_escape')

In [12]:
stock.tail()

              Date     Price      Open      High       Low Vol. Change %
2761  Jan 09, 2009  8,599.18  8,738.80  8,800.45  8,541.75    -   -1.64%
2762  Jan 08, 2009  8,742.46  8,769.94  8,807.14  8,593.52    -   -0.31%
2763  Jan 07, 2009  8,769.70  8,996.94  8,996.94  8,690.45    -   -2.72%
2764  Jan 06, 2009  9,015.10  8,954.57  9,175.19  8,868.07    -    0.69%
2765  Jan 05, 2009  8,952.89  9,027.13  9,093.47  8,841.70    -   -0.91%

In [13]:
news.tail()

,Date,Open,High,Low,Close*,Adj Close**,Volume
1254,"Jul 11, 2016","18,161.53","18,283.90","18,161.53","18,226.93","18,226.93","8,08,80,000"
1255,"Jul 08, 2016","17,971.22","18,166.77","17,971.22","18,146.74","18,146.74","9,34,60,000"
1256,"Jul 07, 2016","17,924.24","17,984.95","17,816.65","17,895.88","17,895.88","8,15,70,000"
1257,"Jul 06, 2016","17,807.47","17,926.91","17,713.45","17,918.62","17,918.62","9,30,00,000"
1258,"Jul 05, 2016","17,904.45","17,904.45","17,785.28","17,840.62","17,840.62","10,36,50,000"

In [14]:
news.shape

(1259, 7)

In [15]:
merge = stock.merge(news, how='inner', on='Date')

In [16]:
merge

,Date,Price,Open_x,High_x,Low_x,Vol.,Change %,Open_y,High_y,Low_y,Close*,Adj Close**,Volume
0,"Dec 31, 2019","28,538.44","28,414.64","28,547.35","28,376.49",193.34M,0.27%,"28,414.64","28,547.35","28,376.49","28,538.44","28,538.44","19,33,40,000"
1,"Dec 30, 2019","28,462.14","28,654.76","28,664.69","28,428.98",185.07M,-0.64%,"28,654.76","28,664.69","28,428.98","28,462.14","28,462.14","18,16,00,000"
2,"Dec 27, 2019","28,645.26","28,675.34","28,701.66","28,608.98",184.93M,0.08%,"28,675.34","28,701.66","28,608.98","28,645.26","28,645.26","18,22,80,000"
3,"Dec 26, 2019","28,621.39","28,539.46","28,624.10","28,535.15",155.97M,0.37%,"28,539.46","28,624.10","28,535.15","28,621.39","28,621.39","15,59,70,000"
4,"Dec 24, 2019","28,515.45","28,572.57","28,576.80","28,503.21",95.29M,-0.13%,"28,572.57","28,576.80","28,503.21","28,515.45","28,515.45","8,61,50,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,"Jul 11, 2016","18,226.93","18,161.53","18,283.90","18,161.53",80.88M,0.44%,"18,161.53","18,283.90","18,161.53","18,226.93","18,226.93","8,08,80,000"
876,"Jul 08, 2016","18,146.74","17,971.22","18,166.77","17,971.22",93.46M,1.40%,"17,971.22","18,166.77","17,971.22","18,146.74","18,146.74","9,34,60,000"
877,"Jul 07, 2016","17,895.88","17,924.24","17,984.95","17,816.65",81.58M,-0.13%,"17,924.24","17,984.95","17,816.65","17,895.88","17,895.88","8,15,70,000"
878,"Jul 06, 2016","17,918.62","17,807.47","17,926.91","17,713.45",93.00M,0.44%,"17,807.47","17,926.91","17,713.45","17,918.62","17,918.62","9,30,00,000"
879,"Jul 05, 2016","17,840.62","17,904.45","17,904.45","17,785.28",103.67M,-0.61%,"17,904.45","17,904.45","17,785.28","17,840.62","17,840.62","10,36,50,000"